### ISSUE TITLE
thick wall version

### ISSUE THREAD

**Issue by fi0** [ConstantinoSchillebeeckx/cherry-mx-keycaps#2]
Is the thick wall version thickest / tightest? Or can I further increase the thickness?

**Comment by ConstantinoSchillebeeckx** [comment]
It's about as tight as it can get:
![screen shot 2018-02-12 at 10 16 12 am](https://user-images.githubusercontent.com/8518288/36106821-fce68a4c-0fdd-11e8-964d-4dd6d9de5446.png)
![screen shot 2018-02-12 at 10 16 29 am](https://user-images.githubusercontent.com/8518288/36106823-fd327920-0fdd-11e8-99ee-68e72fed721b.png)

**Comment by fi0** [comment]
thank you! it looks great.
Curious how to generate the above image?

**Comment by ConstantinoSchillebeeckx** [comment]
I'm using [Fusion 360 section view](https://knowledge.autodesk.com/support/fusion-360/learn-explore/caas/CloudHelp/cloudhelp/ENU/Fusion-Function/files/GUID-B78EA5AB-9AF1-4576-A37F-A70BAC51D711-htm.html)

**Comment by fi0** [comment]
👍
