### ISSUE TITLE
diagram saying what row goes where would be nice :P

### ISSUE THREAD

**Issue by increpare** [ConstantinoSchillebeeckx/cherry-mx-keycaps#4]
You might thing people would know.  You might think people online are consistent in naming rows online.  

![key_row_hint](https://user-images.githubusercontent.com/465632/76423766-8e852480-63a7-11ea-84b6-b20b92e7909d.png)

[also, thanks a bunch for this - working on my own keycaps from it right now with a friend :)

![Unknown-2](https://user-images.githubusercontent.com/465632/76423852-abb9f300-63a7-11ea-8668-07db0e3a18fe.jpg)

]

**Comment by increpare** [comment]
gratuitous update:

![photo5460829211108420937](https://user-images.githubusercontent.com/465632/77651671-6d0e6600-6f6d-11ea-9d2f-00da6083aa9e.jpg)

I used a black [Lacquer-Stik](https://markal.com/products/lacquer-stik) to fill in the "engraved" bits.

![photo5460875042704436528](https://user-images.githubusercontent.com/465632/77651679-6ed82980-6f6d-11ea-84af-ce3d1946c930.jpg)

![photo5460829211108420938](https://user-images.githubusercontent.com/465632/77651686-713a8380-6f6d-11ea-95ef-46242cf72a59.jpg)

![photo5461080539709680995](https://user-images.githubusercontent.com/465632/77651696-739cdd80-6f6d-11ea-9171-dc93fe94cc01.jpg)

And the final keyboard:

![20200326_142633](https://user-images.githubusercontent.com/465632/77653135-aba52000-6f6f-11ea-9d2a-1e236fc559e2.jpg)

Thanks :)

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Nice! Thanks for the update 😸
