### ISSUE TITLE
+ holes too small after print. 

### ISSUE THREAD

**Issue by PedramH** [ConstantinoSchillebeeckx/cherry-mx-keycaps#5]
I printed one of the models but it's too tight and I can't mount it on my switches (Cherry MX RED). I checked the dimensions of the models and it's exactly matching the switches. I think it should be a little bigger? 
Could you please provide modifiable cad files (sldprt for example) so everyone can calibrate the dimensions based on their printer and switches?

**Comment by ConstantinoSchillebeeckx** [comment]
@PedramH I have [STEP](https://github.com/ConstantinoSchillebeeckx/cherry-mx-keycaps/tree/master/STEP) files available; does that suit your needs? I used Fusion 360 to model these so I don't have any export options:

![image](https://user-images.githubusercontent.com/8518288/109088065-af3faa80-76dc-11eb-9957-88ff2e255f8b.png)

**Comment by Dawnaur** [comment]
I got the same problem here, and... well, I noticed according to the brand, my switchs' cross are 1.0mm to 1.25mm thin.

The files are 1.1mm thin, and with printer's approximation, it will be less.
In my case, after printing, the 1.1mm became 0,9mm, but it should be around 0.95mm to 1.0mm on a better printer.
This way, I think the file should describe 1.40mm thin cross to be printable and usable on near all switches.

I tried using the thin version step file (there is no step for thick version), but I don't manage to get a good result as I haven't the building tree.
Maybe this is possible without build tree, I don't know and I have to admit my modeling skills are limited.

Do you think you can make the modification (maybe in a new 3dprint branch), or provide f3d file(s) ?

**Comment by ConstantinoSchillebeeckx** [comment]
As previously mentioned, you can find 3d STEP files in the repo.
